apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-classroom-secrets
  namespace: my-classroom
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: infisical
  target:
    name: my-classroom-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: APP_SECRET
